// Warning: this file is generated by LLM by reading the file `bezier.py` in janim

#[inline]
fn cross_2d(v1: [f32; 2], v2: [f32; 2]) -> f32 {
    v1[0] * v2[1] - v1[1] * v2[0]
}

fn find_intersection(p0: [f32; 2], v0: [f32; 2], p1: [f32; 2], v1: [f32; 2]) -> [f32; 2] {
    let p1_p0 = [p1[0] - p0[0], p1[1] - p0[1]];
    let numer = cross_2d(v1, p1_p0);
    let mut denom = cross_2d(v1, v0);

    if denom.abs() < 1e-5 {
        denom = f32::INFINITY; // So that ratio goes to 0 there
    }
    let ratio = numer / denom;

    [p0[0] + ratio * v0[0], p0[1] + ratio * v0[1]]
}

fn eval_cubic_bezier(a0: [f32; 2], h0: [f32; 2], h1: [f32; 2], a1: [f32; 2], t: f32) -> [f32; 2] {
    let mt = 1.0 - t;
    let c0 = mt.powi(3);
    let c1 = 3.0 * mt.powi(2) * t;
    let c2 = 3.0 * mt * t.powi(2);
    let c3 = t.powi(3);
    [
        c0 * a0[0] + c1 * h0[0] + c2 * h1[0] + c3 * a1[0],
        c0 * a0[1] + c1 * h0[1] + c2 * h1[1] + c3 * a1[1],
    ]
}

fn eval_quadratic_bezier(v0: [f32; 2], v1: [f32; 2], v2: [f32; 2], t: f32) -> [f32; 2] {
    let mt = 1.0 - t;
    let c0 = mt.powi(2);
    let c1 = 2.0 * mt * t;
    let c2 = t.powi(2);
    [
        c0 * v0[0] + c1 * v1[0] + c2 * v2[0],
        c0 * v0[1] + c1 * v1[1] + c2 * v2[1],
    ]
}

pub fn get_quadratic_approximation_of_cubic(
    a0: [f32; 2],
    h0: [f32; 2],
    h1: [f32; 2],
    a1: [f32; 2],
) -> [[f32; 2]; 5] {
    // Tangent vectors at the start and end.
    let t0 = [h0[0] - a0[0], h0[1] - a0[1]];
    let t1 = [a1[0] - h1[0], a1[1] - h1[1]];

    let p = [h0[0] - a0[0], h0[1] - a0[1]];
    let q = [h1[0] - 2.0 * h0[0] + a0[0], h1[1] - 2.0 * h0[1] + a0[1]];
    let r = [
        a1[0] - 3.0 * h1[0] + 3.0 * h0[0] - a0[0],
        a1[1] - 3.0 * h1[1] + 3.0 * h0[1] - a0[1],
    ];

    let a = cross_2d(q, r);
    let b = cross_2d(p, r);
    let c = cross_2d(p, q);

    // Search for inflection points.  If none are found, use the midpoint as a cut point.
    // Based on http://www.caffeineowl.com/graphics/2d/vectorial/cubic-inflexion.html
    let disc = b * b - 4.0 * a * c;
    let mut t_mid = 0.5;

    if disc > 1e-4 {
        let sqrt_disc = disc.abs().sqrt();

        // Choose a value of t which starts at 0.5,
        // but is updated to one of the inflection points
        // if they lie between 0 and 1
        let mut check_and_update = |ti: f32| {
            if ti > 0.0 && ti < 1.0 {
                t_mid = ti;
            }
        };

        if a == 0.0 {
            if b != 0.0 {
                check_and_update(-c / b);
            }
        } else {
            check_and_update((-b - sqrt_disc) / (2.0 * a));
            check_and_update((-b + sqrt_disc) / (2.0 * a));
        }
    }

    // Compute bezier point and tangent at the chosen value of t
    let mid = eval_cubic_bezier(a0, h0, h1, a1, t_mid);

    let tm_v0 = [h0[0] - a0[0], h0[1] - a0[1]];
    let tm_v1 = [h1[0] - h0[0], h1[1] - h0[1]];
    let tm_v2 = [a1[0] - h1[0], a1[1] - h1[1]];
    let tm = eval_quadratic_bezier(tm_v0, tm_v1, tm_v2, t_mid);

    // Intersection between tangent lines at end points and tangent in the middle
    let i0 = find_intersection(a0, t0, mid, tm);
    let i1 = find_intersection(a1, t1, mid, tm);

    [a0, i0, mid, i1, a1]
}
